### ISSUE TITLE
how to make

### ISSUE THREAD

**Issue by huison-cao** [zhobo63/imgui-ts#1]
bind-imgui.cpp:2256:30: error: no viable overloaded '='
                _out_text[0] = emscripten::val(ctx->_ImGui_Combo_text);
bind-imgui.cpp:18:52: note: expanded from macro 'FUNCTION'
    emscripten::optional_override([] ARGS -> RET { CODE })
                                                   ^~~~
bind-imgui.cpp:18:52: note: expanded from macro 'FUNCTION'
    emscripten::optional_override([] ARGS -> RET { CODE })
                                                   ^~~~
D:\Application\emsdk\upstream\emscripten\cache\sysroot/include\emscripten/val.h:408:14: note: candidate function not viable: expects
      an lvalue for object argument
        val& operator=(val&& v) & {
             ^
D:\Application\emsdk\upstream\emscripten\cache\sysroot/include\emscripten/val.h:415:14: note: candidate function not viable: expects
      an lvalue for object argument
        val& operator=(const val& v) & {
             ^
bind-imgui.cpp:2661:30: error: no viable overloaded '='
                _out_text[0] = emscripten::val(ctx->_ImGui_ListBox_B_text);
                ~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bind-imgui.cpp:18:52: note: expanded from macro 'FUNCTION'
    emscripten::optional_override([] ARGS -> RET { CODE })
                                                   ^~~~
bind-imgui.cpp:18:52: note: expanded from macro 'FUNCTION'
    emscripten::optional_override([] ARGS -> RET { CODE })
                                                   ^~~~
D:\Application\emsdk\upstream\emscripten\cache\sysroot/include\emscripten/val.h:408:14: note: candidate function not viable: expects
      an lvalue for object argument
        val& operator=(val&& v) & {
             ^
D:\Application\emsdk\upstream\emscripten\cache\sysroot/include\emscripten/val.h:415:14: note: candidate function not viable: expects
      an lvalue for object argument
        val& operator=(const val& v) & {

**Comment by WanderWang** [comment]
the same issue . Anyone slove this problem ?

**Comment by WanderWang** [comment]
problem sloved .
I use an older emscripten version (  ```./emsdk install 1.38.20``` )   instead of latest
