### ISSUE TITLE
Different questions

### ISSUE THREAD

**Issue by yannbcf** [zhobo63/imgui-ts#4]
Hello,

first thanks a lot for this repository, it allowed me to discover ImGui trough the web and it's super useful for my usecase.

Will you maintain the repo and update the ImGui version to the latest from times to times ?
Why are some styles readonly, like ItemSpacing ?

**Comment by CodingButter** [comment]
> Hello,
> 
> first thanks a lot for this repository, it allowed me to discover ImGui trough the web and it's super useful for my usecase.
> 
> Will you maintain the repo and update the ImGui version to the latest from times to times ? Why are some styles readonly, like ItemSpacing ?

I Cant wait to use this package. Thank you Zhobo so much. 

I'm struggling to incorporate this into my project. Would you be willing to help me. I'm very knew to web-assembly and I'm trying to wrap my head around what I need to do to get this package usable in my project. I would compensate for any help. 

Again, thanks so much for the selfless contribution to the community!

**Comment by zhobo63** [comment]
there are also npm package @zhobo63/imgui-ts
https://www.npmjs.com/package/@zhobo63/imgui-ts
